---
run:
  timeout: 10m
  concurrency: 4
  skip-dirs-use-default: false
linters:
  disable-all: true
  enable:
    - gofmt
    - govet
    - unconvert
    - staticcheck
    - ineffassign
    - unparam
    - forbidigo
linters-settings:
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
      - nilness
      - shadow
      - unusedwrite
  gofmt:
    simplify: true
  forbidigo:
    forbid:
      - '\bioutil\b(# Use io and os packages instead of ioutil)?'
      - '\brequire\.New\b(# Use package-level functions with explicit TestingT)?'
      - '\bassert\.New\b(# Use package-level functions with explicit TestingT)?'